filter:
  excluded_paths:
      - 'ieducar/tests/*'
      - 'ieducar/misc/**/*'
      - 'ieducar/intranet/scripts/jquery'
      - 'ieducar/intranet/scripts/scriptaculous'
      - 'ieducar/intranet/scripts/prototype'
      - 'ieducar/intranet/scripts/select2'
      - 'ieducar/intranet/scripts/graficos'
      - 'ieducar/modules/Portabilis/Assets/Plugins/AjaxChosen/'
      - 'ieducar/modules/Portabilis/Assets/Plugins/Chosen/'

checks:
  php:
    code_rating: true

tools:
    external_code_coverage: true
    php_analyzer: true
    php_changetracking: true
    php_code_sniffer:
      config:
        standard: "PSR2"
    php_cpd: true
    php_mess_detector: true
    php_pdepend: true
    sensiolabs_security_checker: true

build:
  environment:
    postgresql: true

  dependencies:
    after:
      - psql -c "CREATE DATABASE ieducar_test WITH OWNER = scrutinizer ENCODING = 'UTF8' LC_COLLATE = 'en_US.UTF-8' TEMPLATE template0"
      - cp phinx.php.scrutinizer phinx.php
      - ieducar/vendor/bin/phinx seed:run -s StartingSeed -s StartingForeignKeysSeed
      - ieducar/vendor/bin/phinx migrate

