version: '3'

services:
  web:
    build: ./docker/apache/
    volumes:
      - ./:/usr/local/apache2/htdocs/
      - ./docker/apache/docker.apache.conf:/usr/local/apache2/conf.d/docker.apache.conf
      - ./docker/apache/logs/:/usr/local/apache2/logs
    ports:
      - 8001:80
    links:
      - php
  php:
    build: ./docker/php
    env_file:
      - .env
    volumes:
      - .:/var/www
    links:
      - postgres
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
  composer:
    image: "composer"
    volumes:
      - ./:/app
    command: install
  postgres:
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    image: postgres:9.5
    environment:
      - POSTGRES_USER=ieducar
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5434:5432
    container_name: postgres
  pgadmin:
    image: fenglc/pgadmin4
    container_name: pgadmin
    restart: always
    ports:
      - "5050:5050"
    volumes:
      - ./volumes/pgadmin/config:/pgadmin/config
      - ./volumes/pgadmin/storage:/pgadmin/storage
    links:
      - postgres:postgres
