version: '3'

services:

  nginx:
    image: nginx:alpine
    container_name: ieducar-nginx
    links:
      - php
    ports:
      - 80:80
    working_dir: /var/www/ieducar
    volumes:
      - ./:/var/www/ieducar
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf

  php:
    container_name: ieducar-php
    hostname: ieducar-php
    build: docker/php
    links:
      - postgres_municipio_1
      - postgres_municipio_2
      - redis
    ports:
      - 9000
    environment:
      #PGPASSWORD: ieducar
      XDEBUG_IDEKEY: VSCODE
      XDEBUG_CLIENT_HOST: host.docker.internal
      XDEBUG_CLIENT_PORT: 9003
      XDEBUG_MODE: debug
      XDEBUG_START_WITH_REQUEST: "yes"
    working_dir: /var/www/ieducar
    volumes:
      - ./:/var/www/ieducar
    extra_hosts: 
      - "host.docker.internal:host-gateway"

  postgres:
    container_name: ieducar-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: ieducar
      POSTGRES_USER: ieducar
      POSTGRES_PASSWORD: ieducar
    ports:
      - 5432
    volumes:
      - ./database/data/postgres:/var/lib/postgresql/data

  postgres_municipio_1:
    container_name: ieducar-postgres_municipio_1
    image: postgres:alpine
    environment:
      POSTGRES_DB: ieducar_1
      POSTGRES_USER: ieducar_1
      POSTGRES_PASSWORD: ieducar_1
    ports:
      - 15432:5432
    volumes:
      - ./database/data/postgres_municipio_1:/var/lib/postgresql/data

  postgres_municipio_2:
    container_name: ieducar-postgres_municipio_2
    image: postgres:alpine
    environment:
      POSTGRES_DB: ieducar_2
      POSTGRES_USER: ieducar_2
      POSTGRES_PASSWORD: ieducar_2
    ports:
      - 25432:5432
    volumes:
      - ./database/data/postgres_municipio_2:/var/lib/postgresql/data

  redis:
    container_name: ieducar-redis
    image: redis:alpine
    restart: always
    ports:
      - 6379
