version: '3'

services:

  postgres:
    image: postgres:14-alpine
    container_name: ieducar-postgres
    restart: unless-stopped
    environment:
      - SERVICE_TAGS=dev
      - SERVICE_NAME=postgres
      - POSTGRES_DB=ieducar
      - POSTGRES_USER=ieducar
      - POSTGRES_PASSWORD=ieducar
    ports:
      - "5432"
    volumes:
      - ./database/postgresql/data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    container_name: ieducar-redis
    restart: unless-stopped
    environment:
      - SERVICE_TAGS=dev
      - SERVICE_NAME=redis
    ports:
      - "6379"
    volumes:
      - ./database/redis/data/redis:/data

  nginx:
    build: docker/nginx
    container_name: ieducar-nginx
    ports:
      - "80"
      - "443"
    working_dir: /var/www/ieducar
    links:
      - php
    volumes:
      - ./:/var/www/ieducar

  php:
    build: ./docker/php/8.1/fpm-alpine
    container_name: ieducar-php
    ports:
      - "9000"
      - "9003"
    environment:
      - SERVICE_TAGS=dev
      - SERVICE_NAME=php
      - PGPASSWORD=ieducar
      - PHP_IDE_CONFIG=serverName=i-Educar
      - XDEBUG_CONFIG=remote_host=127.0.0.1'
    working_dir: /var/www/ieducar
    links:
      - postgres
      - redis
    volumes:
      - ./:/var/www/ieducar