version: '3'

services:

  nginx:
    image: nginx:alpine
    container_name: ieducar-nginx
    links:
      - php
    ports:
      - 80
    working_dir: /var/www/ieducar
    volumes:
      - ./:/var/www/ieducar
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/upstream.conf:/etc/nginx/conf.d/upstream.conf

  php:
    container_name: ieducar-php
    build: docker/php
    links:
      - postgres
      - redis
    environment:
      PGPASSWORD: ieducar
    working_dir: /var/www/ieducar
    volumes:
      - ./:/var/www/ieducar

  postgres:
    container_name: ieducar-postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: ieducar
      POSTGRES_USER: ieducar
      POSTGRES_PASSWORD: ieducar
    ports:
      - 5432
    volumes:
      - ./database/data:/var/lib/postgresql/data

  redis:
    container_name: ieducar-redis
    image: redis:alpine
    restart: always
    ports:
      - 6379
