version: '3'

services:
  web:
    build: ./docker/apache/
    volumes:
      - ./:/usr/local/apache2/htdocs/
      - ./docker/apache/docker.apache.conf:/usr/local/apache2/conf.d/docker.apache.conf
      - ./docker/apache/logs/:/usr/local/apache2/logs
    ports:
      - 80:80
    links:
      - php
  php:
    build: ./docker/php
    env_file:
      - .env
    volumes:
      - .:/var/www
    links:
      - postgres
    environment:
      XDEBUG_CONFIG: "remote_host=172.17.0.1 remote_enable=1"
  composer:
    image: "composer"
    volumes:
      - ./:/app
    command: install
  postgres:
    volumes:
      - ./docker/postgres/volume/data:/var/lib/postgresql/data
    image: postgres:9.5
    environment:
      - POSTGRES_USER=ieducar
      - POSTGRES_PASSWORD=ieducar
    ports:
      - 5432:5432
    container_name: postgres
